<?xml version="1.0" encoding="utf-8"?>
<Project>
  <Import Project="Sdk.props" 
          Sdk="Microsoft.DotNet.Arcade.Sdk" />

  <PropertyGroup>
    <PackageIconUrl>http://go.microsoft.com/fwlink/?LinkID=288859</PackageIconUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <!-- Test config -->
  <PropertyGroup>
    <!-- Arcade config -->
    <TestToolsSuffix>-preview.25074.1</TestToolsSuffix>
    <MSTestVersion>3.8.0$(TestToolsSuffix)</MSTestVersion>
    <MTPVersion>1.6.0$(TestToolsSuffix)</MTPVersion>
    <TestRunnerName>MSTest</TestRunnerName>
    <UseMSTestMetaPackage>true</UseMSTestMetaPackage>
    <UseMSTestRunner>true</UseMSTestRunner>
    <!-- MSTest config -->
    <EnableMSTestRunner>true</EnableMSTestRunner>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <MSTestAnalysisMode>Recommended</MSTestAnalysisMode>
  </PropertyGroup>

</Project>
